unjs/changelogen

src/config.ts, src/git.ts
When you on a tag, `getCurrentGitBranch` failed to grab the tag name and results `to` to be `HEAD`
```bash
changelogen on  tags/v0.1.0 is 📦 v0.1.0 via ⬢ v16.14.2 
➜ git checkout tags/v0.1.0       
HEAD is now at 79d6a90 chore(release): 0.1.0
changelogen on  tags/v0.1.0 is 📦 v0.1.0 via ⬢ v16.14.2 
➜ git rev-parse --abbrev-ref HEAD
HEAD
changelogen on  tags/v0.1.0 is 📦 v0.1.0 via ⬢ v16.14.2 
➜ git tag --points-at HEAD 
v0.1.0
```
=> fix: use `getCurrentGitRef`

src/config.ts
I expect to generate only *CHANGELOG.md* which is defaults by below:
```sh
npx changelogen@latest --output
```
Actually, it throws error since `--output` is `true` but `CHANGELOG.md`.
As workaround, I use `npx changelogen@latest --output > xxx.md` for my purpose.
Would it be more appropriate to set  `--output` 's true to `CHANGELOG.md`?
=> fix: let `--output` work without value

src/git.ts
On Nuxt framework repo, for example, we have multiple branches. `2.x` branch continues having new tags, but these are irrelevant for `main` branch. This updates git command to use only the latest accessible tag.
=> fix: only access latest tag accessible from current branch

.eslintrc, README.md, package.json, pnpm-lock.yaml, src/cli.ts, src/commands/default.ts, src/commands/github.ts, src/config.ts, src/github.ts, src/index.ts, src/markdown.ts, src/repo.ts, test/fixtures/CHANGELOG.md, test/markdown.test.ts
Usage: 
```sh
changelogen gh release <versions...>
```
(more usage is updated in the docs)
=> feat: github release integration

src/commands/default.ts
resolve Cannot read properties of undefined (reading 'provider') if no repo is provided
=> fix: handle unset value for `config.repo`

README.md, src/commands/default.ts, src/semver.ts
Add bump pre version, It can set with arguments: `--premajor`, `--preminor`, `--prepatch`, `--prerelease`
ex: `changelogen --bump --premajor` or `changelogen --bump --premajor=alpha`
=> feat: bump pre version

src/markdown.ts, test/git.test.ts
Removes unnecessary line break after `[compared changes]` and unnecessary leading double space before each commit item.
Prettier keeps reformatting it this way after I generate the changelog via `--bump`
Before:
```
[compare changes](https://github.com/unjs/changelogen/compare/v0.4.0...v0.4.1)
- Bump by patch by default ([7e38438](https://github.com/unjs/changelogen/commit/7e38438))
```
After:
```
[compare changes](https://github.com/unjs/changelogen/compare/v0.4.0...v0.4.1)
- Bump by patch by default ([7e38438](https://github.com/unjs/changelogen/commit/7e38438))
```
Notes:
- the current test fixture already displays this "clean" formatting: https://github.com/unjs/changelogen/blob/main/test/fixtures/CHANGELOG.md
- I'd be happy to update my other PR #103 if you go ahead with this one. Or …
=> fix(markdown): remove unnecessary spaces

src/commands/github.ts, src/config.ts, src/github.ts, src/markdown.ts, src/repo.ts
Allow the `repo` option to be string, and then resolve it with `getRepoConfig`
=> feat: `repo` option as string

README.md, src/commands/default.ts, src/git.ts
Adds a `--clean` parameter.  When specified, checks the working directory and exits if it is not clean.
=> feat: add param to require clean working dir (#92)

src/config.ts, src/markdown.ts
Checks for any of the strings in name or email to exclude them from authors.
Also, can disable contributors section with `excludeAuthors: ['']`
Closes #58
=> feat: add excludeAuthors option (#58)

src/github.ts
This will also work with JWTs: https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28#about-authentication.
I didn't encounter an issue here but the GH docs do say that this is preferred.
=> fix(github): use bearer token 

src/git.ts, test/git.test.ts
- Resolve #145 
Although not part of the `conventionalcommits` standard, it is common practice for git messages to be prefixed with emoji.
This PR allows parsing prefixed string emoji (e.g., `:bug:`) and Unicode emoji (e.g., 🐞).
I ran unit tests to make sure it wouldn't affect the original parsing. I also wrote the appropriate unit tests for emoji parsing.
**Need for discussion**
Theoretically, unless someone uses emoji to prevent commits from being added to the changelog, it's senseless. So I just modified the original regex.
If we must obey `conventionalcommits`, we may need to expose the regex to config.
=> feat(git): support parse git messages that have prefix emoji

src/repo.ts, test/repo.test.ts
Resolves #218
Reproduction steps described in the issue. If preferred can also be reproduced in the unit tests after the fix is reverted.
=> fix: handle repo name with multiple segments

src/semver.ts
Resolve regression with #223
npm **cleans up** (!) the `+*` part
=> fix(bump): avoid using `+` for canary suffix

src/git.ts, test/git.test.ts
=> feat: add check for breaking changes in commit body

README.md, src/config.ts, src/markdown.ts
Add a new flag which allows to hide the email addresses for authors.
This PR resolves #246.
=> feat: hide author email address via flag

src/markdown.ts
Resolves #258
Short hint:
Changelogen GitHub release creation does not support pre-release versions like `v1.0.0-rc.0` or `v1.0.0-0`.
Strangely, it can bump a version to something like this, which is then is not supported during GitHub release creation.
=> fix: release version regex supporting pre versions

src/commands/github.ts
show only usernames in GitHub release body for better rendering
=> fix: render usernames in github changelog

src/commands/default.ts, src/config.ts, src/git.ts, src/package.ts
noticed when running `changelogen` programmatically for a new feature in nuxt/ecosystem-ci - some commands respected the `cwd` but others did not.
=> fix: pass `cwd` in more places before running commands

src/commands/default.ts, src/markdown.ts, test/contributors.test.ts
Follow up of #247, resolves #246
This PR improves the configuration of the `hideAuthorEmail` flag to make it work correctly. Before the flag was not properly applied to the logic. The PR also adds a test to ensure that it works.
=> fix(cli): accept `hideAuthorEmail` arg
